#!/usr/bin/env bash
#SBATCH -J 'ff_0'
#SBATCH -o outputs/slurm-%j-experiment3.out
#SBATCH -p all
#SBATCH -t 1400
#SBATCH -N 1
#SBATCH --ntasks-per-node=4
#SBATCH --gres=gpu:1

module load anaconda/4.4.0
source activate thesis
module load cudnn/cuda-9.0/7.0.3
module load cudatoolkit/9.0

# Probe for statistics.
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN --test_filename=test_QSubject_replacesubject.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=LSTM-LN --test_filename=test_QSubject_replacesubject.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN-FW --test_filename=test_QSubject_replacesubject.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QSubject_replacesubject.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN --test_filename=test_QSubject_paduntilsubject.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=LSTM-LN --test_filename=test_QSubject_paduntilsubject.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN-FW --test_filename=test_QSubject_paduntilsubject.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QSubject_paduntilsubject.p --trial_num=0

python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN --test_filename=test_QFriend_replacefriend.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=LSTM-LN --test_filename=test_QFriend_replacefriend.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN-FW --test_filename=test_QFriend_replacefriend.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QFriend_replacefriend.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN --test_filename=test_QFriend_paduntilfriend.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=LSTM-LN --test_filename=test_QFriend_paduntilfriend.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN-FW --test_filename=test_QFriend_paduntilfriend.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QFriend_paduntilfriend.p --trial_num=0

python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN --test_filename=test_QPoet_replacepoet.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=LSTM-LN --test_filename=test_QPoet_replacepoet.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN-FW --test_filename=test_QPoet_replacepoet.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QPoet_replacepoet.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN --test_filename=test_QEmcee_replaceemcee.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=LSTM-LN --test_filename=test_QEmcee_replaceemcee.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN-FW --test_filename=test_QEmcee_replaceemcee.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QEmcee_replaceemcee.p --trial_num=0

python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN --test_filename=test_QPoet_replacefriend.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=LSTM-LN --test_filename=test_QPoet_replacefriend.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=RNN-LN-FW --test_filename=test_QPoet_replacefriend.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=probe_statistics --exp_name=generate_train3roles_testnewrole_withunseentestfillers_1000personspercategory_24000train_120test_add05fillers --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QPoet_replacefriend.p --trial_num=0

# Look at write weights.
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=variablefiller_gensymbolicstates_100000_1_testunseen_QSubject --filler_type=variable_filler --model_name=NTM2 --test_filename=test_analyze.p --trial_num=0
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=variablefiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=variable_filler --model_name=NTM2 --test_filename=test_analyze.p --trial_num=0

#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=variablefiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=variable_filler --model_name=NTM2 --test_filename=test_analyze.p --trial_num=0
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=variablefiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=variable_filler --model_name=NTM2 --test_filename=test_QEmcee.p --trial_num=0
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=variablefiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=variable_filler --model_name=NTM2 --test_filename=test_QFriend.p --trial_num=0
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=variablefiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=variable_filler --model_name=NTM2 --test_filename=test_QPoet.p --trial_num=0
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=variablefiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=variable_filler --model_name=NTM2 --test_filename=test_QSubject.p --trial_num=0
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=variablefiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=variable_filler --model_name=NTM2 --test_filename=test_QDessert_bought.p --trial_num=0
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=variablefiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=variable_filler --model_name=NTM2 --test_filename=test_QDrink_bought.p --trial_num=0

#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=fixedfiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QFriend.p --trial_num=0
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=fixedfiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QPoet.p --trial_num=0
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=fixedfiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QSubject.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=fixedfiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QDessert_bought.p --trial_num=0
python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=fixedfiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QDrink_bought.p --trial_num=0
#python -u /home/cc27/Thesis/generalized_schema_learning/run_experiment.py --function=analyze --exp_name=fixedfiller_gensymbolicstates_100000_1_testunseen_AllQs --filler_type=fixed_filler --model_name=NTM2 --test_filename=test_QEmcee.p --trial_num=0

